apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: thalassa-dbaas-manager
  namespace: flux-system
spec:
  interval: 10m
  timeout: 15m
  targetNamespace: thalassa-dbaas-manager
  install:
    createNamespace: true
  dependsOn:
    - name: thalassa-dbaas-manager-crds
      namespace: flux-system
  chart:
    spec:
      chart: thalassa-dbaas-manager
      version: v0.3.0
      sourceRef:
        kind: HelmRepository
        name: thalassa-cloud-charts
        namespace: flux-system
  values:
    enableServiceMonitor: false
    thalassa:
      enabled: true
      url: https://api.thalassa.cloud
      # Replace with your organisation ID (or use valuesFrom for GitOps secrets).
      organisation: "o-<org-id>"
      authMethod: tokenExchange
      tokenExchange:
        serviceAccountId: "sa-<serviceaccount-id>"
        projectedToken:
          enabled: true
          audience: "https://api.thalassa.cloud"
    serviceAccount:
      create: true
    extraArgs:
      - --default-subnet-id=<subnet-id>
