# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/dbaas.controllers.thalassa.cloud_postgresclusters.yaml
- bases/dbaas.controllers.thalassa.cloud_postgresdatabases.yaml
- bases/dbaas.controllers.thalassa.cloud_postgresroles.yaml
- bases/dbaas.controllers.thalassa.cloud_dbobjectstores.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch
